import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type PdfLine = {
  product: string;
  category: string;
  qty: number;
  price: number;
  discount: number;
};

const INK: [number, number, number] = [16, 26, 46];
const ACCENT: [number, number, number] = [29, 78, 216];
const MUTED: [number, number, number] = [98, 113, 140];

const usd = (n: number) =>
  "$" + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function shell(doc: jsPDF, title: string, subtitle: string) {
  doc.setFillColor(...INK);
  doc.rect(0, 0, 210, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("DealFlow 360", 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(200, 210, 230);
  doc.text("Revenue Operations OS", 14, 20);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(title, 14, 28);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(200, 210, 230);
  doc.text(subtitle, 120, 28);
  doc.setTextColor(...INK);
}

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by DealFlow 360 (demo prototype)", 14, 290);
    doc.text(`Page ${i} of ${pages}`, 196, 290, { align: "right" });
  }
}

function lineRows(lines: PdfLine[]) {
  return lines.map((l) => {
    const net = l.qty * l.price * (1 - l.discount / 100);
    return [l.product, String(l.qty), usd(l.price), `${l.discount.toFixed(1)}%`, usd(net)];
  });
}

export function downloadQuotePdf(input: {
  id: string;
  account: string;
  tier: string;
  date: string;
  lines: PdfLine[];
}) {
  const doc = new jsPDF();
  shell(doc, `Quotation ${input.id}`, `${input.account} (${input.tier})`);
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`Date: ${input.date}   |   Valid 30 days   |   Terms: Net 15`, 14, 42);

  autoTable(doc, {
    startY: 48,
    head: [["Item", "Qty", "List price", "Discount", "Net"]],
    body: lineRows(input.lines),
    theme: "grid",
    headStyles: { fillColor: INK, fontSize: 9 },
    styles: { fontSize: 9, textColor: INK },
  });

  const gross = input.lines.reduce((s, l) => s + l.qty * l.price, 0);
  const net = input.lines.reduce((s, l) => s + l.qty * l.price * (1 - l.discount / 100), 0);
  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  doc.setFontSize(10);
  doc.text(`Gross: ${usd(gross)}`, 14, y);
  doc.text(`Concession: ${usd(gross - net)}`, 14, y + 6);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...ACCENT);
  doc.text(`Net payable: ${usd(net)}`, 14, y + 13);
  doc.setTextColor(...INK);
  footer(doc);
  doc.save(`${input.id}-quotation.pdf`);
}

export function downloadInvoicePdf(input: {
  id: string;
  account: string;
  due: string;
  status: string;
  lines: PdfLine[];
}) {
  const doc = new jsPDF();
  shell(doc, `Invoice ${input.id}`, `${input.account} (Due ${input.due})`);
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`Status: ${input.status}   |   Settlement: Stripe   |   Terms: Net 15`, 14, 42);

  autoTable(doc, {
    startY: 48,
    head: [["Item", "Qty", "List price", "Discount", "Net"]],
    body: lineRows(input.lines),
    theme: "grid",
    headStyles: { fillColor: INK, fontSize: 9 },
    styles: { fontSize: 9, textColor: INK },
  });

  const net = input.lines.reduce((s, l) => s + l.qty * l.price * (1 - l.discount / 100), 0);
  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...ACCENT);
  doc.text(`Amount due: ${usd(net)}`, 14, y);
  doc.setTextColor(...INK);
  footer(doc);
  doc.save(`${input.id}-invoice.pdf`);
}

export function downloadReportPdf(input: {
  period: string;
  kpis: [string, string][];
  pipeline: [string, string, string][];
}) {
  const doc = new jsPDF();
  shell(doc, "Executive Revenue Report", input.period);

  autoTable(doc, {
    startY: 44,
    head: [["Metric", "Value"]],
    body: input.kpis,
    theme: "grid",
    headStyles: { fillColor: INK, fontSize: 9 },
    styles: { fontSize: 9, textColor: INK },
  });

  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Pipeline snapshot", 14, y);

  autoTable(doc, {
    startY: y + 4,
    head: [["Quote", "Account", "Value"]],
    body: input.pipeline,
    theme: "grid",
    headStyles: { fillColor: ACCENT, fontSize: 9 },
    styles: { fontSize: 9, textColor: INK },
  });

  footer(doc);
  doc.save("dealflow360-executive-report.pdf");
}
